apiVersion: v1
kind: Service
metadata:
  name: jke-web
  labels:
    app: jke-web
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 90
    targetPort: 9080
  selector:
    app: jke-web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jke-web
spec:
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   matchLabels:
  #     app: guestbook
  #     tier: frontend
  template:
    metadata:
      labels:
        app: jke-web
    spec:
      containers:
      - name: jke-web
        image: 10.0.0.1/jke/jke.web:@version.name@
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: JKE_DB_HOSTNAME
          value: jke-db
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        ports:
        - containerPort: 9080
      imagePullSecrets:
      - name: local-dtr
