apiVersion: v1
kind: Service
metadata:
  name: jke-db
  labels:
    app: jke-db
spec:
  ports:
    # the port that this service should serve on
  - port: 3306
    targetPort: 3306
  selector:
    app: jke-db
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jke-db
  labels:
    app: jke-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jke-db
    spec:
      containers:
      - name: jke-db
        image: 10.0.0.1/jke/jke.db:@IMAGE_TAG@
        ports:
        - containerPort: 3306
          name: mysql
      imagePullSecrets:
      - name: local-dtr

