apiVersion: v1
kind: Service
metadata:
  name: jke-db
  labels:
    app: @container@
spec:
  ports:
    # the port that this service should serve on
  - port: @service.port@
    targetPort: @service.port@
  selector:
    app: @container@
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jke-db
  labels:
    app: @container@
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: @container@
    spec:
      containers:
      - name: jke-db
        image: @docker.qualified.image@
        ports:
        - containerPort: @service.port@
          name: mysql
      imagePullSecrets:
      - name: local-dtr

